global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node_exporter'
    static_configs:
      - targets: [
          'pg-node-1:9100',     # PostgreSQL nodes
          'pg-node-2:9100',
          'pg-node-3:9100',
          'pg-node-4:9100',
          'etcd-node-1:9100',   # ETCD nodes
          'etcd-node-2:9100',
          'etcd-node-3:9100',
          'pgbouncer-1:9100',   # PgBouncer nodes
          'pgbouncer-2:9100',
          'haproxy:9100'        # HAProxy node
        ]

  - job_name: 'postgres_exporter'
    static_configs:
      - targets: [
          'pg-node-1:9187',     # PostgreSQL nodes
          'pg-node-2:9187',
          'pg-node-3:9187',
          'pg-node-4:9187'
        ]

  - job_name: 'haproxy'
    static_configs:
      - targets: ['localhost:7000']  # HAProxy stats
